// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfDIFW-rRTj_zSYcbzqL22aX6AOMrlU8',
    appId: '1:711603697308:web:fe01ae8d5f68c9c03c5f59',
    messagingSenderId: '711603697308',
    projectId: 'fir-ecommercesampleproject',
    authDomain: 'fir-ecommercesampleproject.firebaseapp.com',
    storageBucket: 'fir-ecommercesampleproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPHItJg5QDT18-IMl9ekVne1Abl4zQNI',
    appId: '1:711603697308:android:5b106fcad53d49d13c5f59',
    messagingSenderId: '711603697308',
    projectId: 'fir-ecommercesampleproject',
    storageBucket: 'fir-ecommercesampleproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DVz-e1iLfOOdx_MNt2oDyb26Mx3C7xY',
    appId: '1:711603697308:ios:6f36b899228e596c3c5f59',
    messagingSenderId: '711603697308',
    projectId: 'fir-ecommercesampleproject',
    storageBucket: 'fir-ecommercesampleproject.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2DVz-e1iLfOOdx_MNt2oDyb26Mx3C7xY',
    appId: '1:711603697308:ios:6f36b899228e596c3c5f59',
    messagingSenderId: '711603697308',
    projectId: 'fir-ecommercesampleproject',
    storageBucket: 'fir-ecommercesampleproject.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfDIFW-rRTj_zSYcbzqL22aX6AOMrlU8',
    appId: '1:711603697308:web:b655118317ac10f83c5f59',
    messagingSenderId: '711603697308',
    projectId: 'fir-ecommercesampleproject',
    authDomain: 'fir-ecommercesampleproject.firebaseapp.com',
    storageBucket: 'fir-ecommercesampleproject.firebasestorage.app',
  );
}
